# expect: spec.backup.schedule
apiVersion: firebird.cloudnative-firebird.io/v1
kind: FirebirdCluster
metadata:
  name: c1
spec:
  instances: 1
  storage:
    size: 1Gi
  backup:
    enabled: true
    schedule: daily
