# expect: valid
apiVersion: firebird.cloudnative-firebird.io/v1
kind: FirebirdRestore
metadata:
  name: r1
spec:
  clusterName: c1
  backupPath: prod/nbackup-l0-x.nbk
  incrementalBackupPaths:
    - prod/nbackup-l1-x.nbk
  restoreType: physical
  s3:
    bucket: b
    secretRef:
      name: s3-creds
