# expect: valid
apiVersion: firebird.cloudnative-firebird.io/v1
kind: FirebirdCluster
metadata:
  name: c1
spec:
  instances: 1
  storage:
    size: 1Gi
  backup:
    enabled: true
    type: physical
    s3:
      bucket: b
      secretRef:
        name: s3-creds
