# expect: valid
apiVersion: firebird.cloudnative-firebird.io/v1
kind: FirebirdBackup
metadata:
  name: r1
spec:
  clusterName: c1
  type: physical
  s3:
    bucket: b
    secretRef:
      name: s3-creds
