apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudnative-firebird-operator
  namespace: cloudnative-firebird-system
  labels:
    app.kubernetes.io/name: cloudnative-firebird
    app.kubernetes.io/component: operator
